on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrvesikar.azurecr.io
        username: ${{ secrets.acr_acrvesikar_username }}
        password: ${{ secrets.acr_acrvesikar_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/packages/landingpage" -f  "packages/landingpage/Dockerfile" -t acrvesikar.azurecr.io/vesikarnextjs-img:${{ github.sha }}
        docker push acrvesikar.azurecr.io/vesikarnextjs-img:${{ github.sha }}

    - name: Set Web App ACR authentication
      uses: Azure/appservice-settings@v1
      with: 
        app-name: vesikar-nextjs
        app-settings-json: | 
          [
            {
              "name": "DOCKER_REGISTRY_SERVER_URL",
              "value": "acrvesikar.azurecr.io",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_USERNAME",
              "value": "${{ secrets.acr_acrvesikar_username }}",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
              "value": "${{ secrets.acr_acrvesikar_password }}",
              "slotSetting": false
            }            
          ]
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: vesikar-nextjs
        images: acrvesikar.azurecr.io/vesikarnextjs-img:${{ github.sha }}